"""
News model for managing blog posts and articles
"""
import uuid
from datetime import datetime
from slugify import slugify
from . import db


class News(db.Model):
    """News model for blog posts and service introductions"""
    
    __tablename__ = 'news'
    
    # Primary key
    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Basic info
    title = db.Column(db.String(200), nullable=False, index=True)
    slug = db.Column(db.String(220), unique=True, nullable=False, index=True)
    summary = db.Column(db.Text)
    
    # Content
    content = db.Column(db.Text, nullable=False)  # HTML content generated by AI or manual
    thumbnail_url = db.Column(db.String(500))
    
    # Metadata
    author = db.Column(db.String(100), default='Hệ thống')
    views_count = db.Column(db.Integer, default=0, nullable=False)
    is_active = db.Column(db.Boolean, default=True, nullable=False)
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    def generate_slug(self):
        """Generate URL-friendly slug from title"""
        if not self.slug and self.title:
            self.slug = slugify(self.title)
    
    def to_dict(self):
        """Convert to dictionary"""
        return {
            'id': self.id,
            'title': self.title,
            'slug': self.slug,
            'summary': self.summary,
            'content': self.content,
            'thumbnail_url': self.thumbnail_url,
            'author': self.author,
            'views_count': self.views_count,
            'is_active': self.is_active,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }

    def __repr__(self):
        return f'<News {self.title}>'
